"""EURUSD candidate selection standards report."""

from __future__ import annotations

from typing import Any

CANDIDATE_STANDARDS = [
    {
        "candidate_type": "short_trend_up_candidate",
        "rule_family": "trend_segment_representative",
        "primary_inputs": ["close_pct_change_3", "close_pct_change_5", "close_pct_change_8", "rolling_range_position_8", "segment_position_fraction"],
        "lookback_window": "3|5|8 + segment span",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 4,
        "reason_codes": ["positive_short_slopes", "high_range_position"],
        "selection_reason_codes": ["segment_representative", "segment_midpoint_anchor", "trend_continuation_context", "sufficient_pre_context"],
        "primary_selection_reason": "segment_midpoint_anchor",
        "known_failure_modes": ["late_segment_anchor", "near_segment_high", "rebound_after_anchor"],
        "current_tail_risk": "medium",
        "review_guidance": "Prefer anchors in 0.25-0.60 segment fraction; reject late-tail or post-anchor reversal rows.",
    },
    {
        "candidate_type": "short_trend_down_candidate",
        "rule_family": "trend_segment_representative",
        "primary_inputs": ["close_pct_change_3", "close_pct_change_5", "close_pct_change_8", "rolling_range_position_8", "segment_position_fraction"],
        "lookback_window": "3|5|8 + segment span",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 4,
        "reason_codes": ["negative_short_slopes", "low_range_position"],
        "selection_reason_codes": ["segment_representative", "segment_midpoint_anchor", "trend_continuation_context", "sufficient_pre_context"],
        "primary_selection_reason": "segment_midpoint_anchor",
        "known_failure_modes": ["late_segment_anchor", "near_segment_low", "rebound_after_anchor"],
        "current_tail_risk": "medium",
        "review_guidance": "Prefer anchors in 0.25-0.60 segment fraction; reject late-tail or post-anchor reversal rows.",
    },
    {
        "candidate_type": "mid_trend_up_candidate",
        "rule_family": "mid_horizon_slope_efficiency",
        "primary_inputs": ["close_pct_change_13", "close_pct_change_21", "efficiency_ratio_21"],
        "lookback_window": "13|21",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 0,
        "reason_codes": ["positive_mid_slopes", "efficiency_above_threshold"],
        "selection_reason_codes": ["positive_mid_slopes", "efficiency_above_threshold"],
        "primary_selection_reason": "efficiency_above_threshold",
        "known_failure_modes": ["late_leg_selection_without_segment_guard"],
        "current_tail_risk": "low",
        "review_guidance": "Treat as structure sample, not entry timing; verify continuity and context.",
    },
    {
        "candidate_type": "mid_trend_down_candidate",
        "rule_family": "mid_horizon_slope_efficiency",
        "primary_inputs": ["close_pct_change_13", "close_pct_change_21", "efficiency_ratio_21"],
        "lookback_window": "13|21",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 0,
        "reason_codes": ["negative_mid_slopes", "efficiency_above_threshold"],
        "selection_reason_codes": ["negative_mid_slopes", "efficiency_above_threshold"],
        "primary_selection_reason": "efficiency_above_threshold",
        "known_failure_modes": ["late_leg_selection_without_segment_guard"],
        "current_tail_risk": "low",
        "review_guidance": "Treat as structure sample, not entry timing; verify continuity and context.",
    },
    {
        "candidate_type": "lower_wick_rejection_candidate",
        "rule_family": "wick_geometry",
        "primary_inputs": ["lower_wick_ratio", "body_ratio", "close", "open"],
        "lookback_window": "1",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 0,
        "reason_codes": ["lower_wick_large", "close_rejected_upper"],
        "selection_reason_codes": ["lower_wick_large", "close_rejected_upper"],
        "primary_selection_reason": "lower_wick_large",
        "known_failure_modes": ["isolated_spike_without_context"],
        "current_tail_risk": "low",
        "review_guidance": "Confirm rejection geometry and local context before accepting.",
    },
    {
        "candidate_type": "upper_wick_rejection_candidate",
        "rule_family": "wick_geometry",
        "primary_inputs": ["upper_wick_ratio", "body_ratio", "close", "open"],
        "lookback_window": "1",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 0,
        "reason_codes": ["upper_wick_large", "close_rejected_lower"],
        "selection_reason_codes": ["upper_wick_large", "close_rejected_lower"],
        "primary_selection_reason": "upper_wick_large",
        "known_failure_modes": ["isolated_spike_without_context"],
        "current_tail_risk": "low",
        "review_guidance": "Confirm rejection geometry and local context before accepting.",
    },
    {
        "candidate_type": "possible_false_breakout_candidate",
        "rule_family": "local_level_break_reclaim",
        "primary_inputs": ["high", "low", "close", "local_high_8", "local_low_8"],
        "lookback_window": "8",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 0,
        "reason_codes": ["break_above_local_high_then_close_inside", "break_below_local_low_then_close_inside"],
        "selection_reason_codes": ["break_above_local_high_then_close_inside", "break_below_local_low_then_close_inside"],
        "primary_selection_reason": "false_breakout_structure",
        "known_failure_modes": ["micro_noise_breaks"],
        "current_tail_risk": "low",
        "review_guidance": "Check whether break/reclaim is structurally meaningful, not random chop.",
    },
    {
        "candidate_type": "doji_indecision_candidate",
        "rule_family": "body_ratio_indecision",
        "primary_inputs": ["body_ratio", "range"],
        "lookback_window": "1",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 0,
        "reason_codes": ["small_body_ratio"],
        "selection_reason_codes": ["small_body_ratio"],
        "primary_selection_reason": "small_body_ratio",
        "known_failure_modes": ["low_range_noise"],
        "current_tail_risk": "low",
        "review_guidance": "Use context tags to separate real indecision from low-volatility noise.",
    },
    {
        "candidate_type": "compression_candidate",
        "rule_family": "range_regime_compression",
        "primary_inputs": ["atr_like_range_mean_8", "atr_like_range_mean_34", "compression_ratio"],
        "lookback_window": "8|34",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 0,
        "reason_codes": ["low_short_vs_long_range"],
        "selection_reason_codes": ["low_short_vs_long_range"],
        "primary_selection_reason": "range_compression",
        "known_failure_modes": ["prolonged_flat_tape"],
        "current_tail_risk": "low",
        "review_guidance": "Confirm compression relative to local regime, not absolute small range only.",
    },
    {
        "candidate_type": "expansion_candidate",
        "rule_family": "range_regime_expansion",
        "primary_inputs": ["range", "atr_like_range_mean_8", "expansion_ratio"],
        "lookback_window": "8",
        "future_window_used_by_candidate_logic": 0,
        "future_window_used_by_review_filter": 0,
        "reason_codes": ["current_range_vs_recent_atr"],
        "selection_reason_codes": ["current_range_vs_recent_atr"],
        "primary_selection_reason": "range_expansion",
        "known_failure_modes": ["single_news_spike"],
        "current_tail_risk": "low",
        "review_guidance": "Check if expansion is sustained context or one-off spike.",
    },
]


def build_validation_eurusd_candidate_selection_standards() -> dict[str, Any]:
    return {
        "status": "ready",
        "candidate_type_count": len(CANDIDATE_STANDARDS),
        "candidate_selection_standards": CANDIDATE_STANDARDS,
    }


def render_validation_eurusd_candidate_selection_standards_markdown(payload: dict[str, Any]) -> str:
    lines = [
        "# EURUSD Candidate Selection Standards",
        "",
        f"- status: `{payload.get('status')}`",
        f"- candidate_type_count: `{payload.get('candidate_type_count')}`",
        "",
        "## Standards",
        "",
    ]
    for row in payload.get("candidate_selection_standards", []):
        lines.extend(
            [
                f"- candidate_type: `{row.get('candidate_type')}`",
                f"  - rule_family: `{row.get('rule_family')}`",
                f"  - lookback_window: `{row.get('lookback_window')}`",
                f"  - future_window_used_by_candidate_logic: `{row.get('future_window_used_by_candidate_logic')}`",
                f"  - future_window_used_by_review_filter: `{row.get('future_window_used_by_review_filter')}`",
                f"  - primary_selection_reason: `{row.get('primary_selection_reason')}`",
                f"  - current_tail_risk: `{row.get('current_tail_risk')}`",
            ]
        )
    return "\n".join(lines) + "\n"
